project:
  type: website

website:
  title: "Game of Thrones Text Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: frequency.qmd
        text: Frequency Analysis
      - href: sentiment.qmd
        text: Sentiment Analysis

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true