project:
  type: website

website:
  title: "Lab 13 on Project 6"
  favicon: assets/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis1.qmd
        text: Analysis 1
      - href: analysis2.qmd
        text: Analysis 2
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true