---
title: "Palmer Penguins"
format: dashboard
server: shiny
---

```{r}
#| context: setup
library(tidyverse)
library(plotly)
library(palmerpenguins)

# Clean data: remove rows where sex is NA
penguins <- filter(penguins, !is.na(sex))
```

## {.sidebar}

```{r}
# select input: variable for x-axis
selectInput(
  inputId = 'xvar', 
  label = 'X-axis:',
  choices = colnames(penguins)[3:6],
  selected = "bill_length_mm")

# select input: variable for y-axis
selectInput(
  inputId = 'yvar', 
  label = 'Y-axis:',
  choices = colnames(penguins)[3:6],
  selected = "bill_depth_mm")

# Input: radio buttons to color code by species
radioButtons(
  inputId = 'colorby',
  label = 'Color by species:',
  choices = c("yes", "no"),
  selected = "no")
```

## Row

```{r}
#| title: "Scatter plot"
plotlyOutput(outputId = 'plot')
```

```{r}
#| context: server
output$plot <- renderPlotly({
  
  # Initialize the ggplot object
  p <- ggplot(data = penguins, aes_string(x = input$xvar, y = input$yvar))
  
  # Check if color coding is requested
  if (input$colorby == "yes") {
    p <- p + geom_point(aes(color = species))
  } else {
    p <- p + geom_point()
  }
  
  # Apply a clean theme and convert to plotly for interactivity
  p <- p + theme_minimal()
  
  ggplotly(p)
})
```
